// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import CurrenciesController from "./currencies_controller"
import ActionsController from "./actions_controller"
import TransactionsController from "./transactions_controller"
import VersionsController from "./versions_controller"

application.register("currencies", CurrenciesController);
application.register("actions", ActionsController);
application.register("transactions", TransactionsController);
application.register("versions", VersionsController);
